# -*- coding: utf-8 -*-
"""ResNet_Laplacian

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B26cqQJiMYRWDGOYS6LnLCiImS5Sf8X_

### Import Dependency
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import keras
from keras.optimizers import RMSprop, SGD, Adam
from keras.models import Sequential
from keras.utils.vis_utils import plot_model
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from keras.models import load_model
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dropout
from tensorflow.keras import regularizers
from tensorflow.keras.applications.resnet import ResNet50
from tensorflow.keras.layers import Layer, Conv2D, Dense, MaxPooling2D, Input, Flatten, BatchNormalization
from tensorflow.keras.layers import Concatenate
from tensorflow.keras.utils import custom_object_scope
from scipy.ndimage import zoom
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import itertools
import random
import numpy as np
import os
import cv2
from PIL import Image
import pandas as pd

"""### Access Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""### Set-up path of the folder"""

# Setup folder path
path_IAM_class =  '/content/drive/MyDrive/IAM_Writer_lines/'

path_IAM_class_Validation = '/content/drive/MyDrive/IAM_Writers_lines_Validation/'

path_IAM_class_test = '/content/drive/MyDrive/IAM_Writer_lines_test/'

# Setup save model path
path_save_model = "/content/drive/MyDrive/SavedModel/ResNet_Laplacian_IAM.h5"

# Setup uploaded Model path
path_uploaded_model = "/content/drive/MyDrive/UploadedModels/ResNet_Laplacian_IAM.h5"

"""### Train Data Generator"""

class SiameseTrainDataGenerator(tf.keras.utils.Sequence):

    def __init__(self, batch_size=16, shuffle=True):
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.data_dir = path_IAM_class
        self.writer_list = sorted(os.listdir(self.data_dir))
        self.img_size = (150, 150)
        self.channels = 3
        self.num_samples = sum(len(os.listdir(os.path.join(self.data_dir, writer_id))) for writer_id in self.writer_list) * 2 # Each image will one genuine and one forged case
        self.writer_lines_list = self.store_image_paths()
        self.on_epoch_end()

    def store_image_paths(self):
      writer_lines_list = []
      for writer_id in self.writer_list:
          writer_dir = os.path.join(self.data_dir, writer_id)
          image_list = os.listdir(writer_dir)
          for image_name in image_list:
              image_path = os.path.join(writer_dir, image_name)
              writer_lines_list.append(image_path)
      return writer_lines_list


    def __len__(self):
        return int(np.ceil(self.num_samples / float(self.batch_size)))

    def __getitem__(self, idx):
        indexes = self.indexes[idx*self.batch_size : (idx+1)*self.batch_size]
        writer_pairs = [self.get_writer_pair(idx) for idx in indexes]
        X1_rgb, X1_edge, X2_rgb, X2_edge, Y = self.__data_generation(writer_pairs)
        return [X1_rgb, X1_edge, X2_rgb, X2_edge], Y

    def on_epoch_end(self):
        self.indexes = np.arange(self.num_samples)
        if self.shuffle:
            np.random.shuffle(self.indexes)

    def get_writer_pair(self, idx):
        img1_path = self.writer_lines_list[idx//2]
        if idx % 2 == 0:
            img2 = np.random.choice(os.listdir(os.path.join(self.data_dir, img1_path.split('/')[-2])))
            while img2 == img1_path.split('/')[-1]:
              img2 = np.random.choice(os.listdir(os.path.join(self.data_dir, img1_path.split('/')[-2])))
            img2_path = os.path.join(self.data_dir, img1_path.split('/')[-2], img2)
            label = 1
        else:
            img_folder = np.random.choice(self.writer_list)
            while img_folder ==  img1_path.split('/')[-2]:
              img_folder = np.random.choice(self.writer_list)
            img2_path = os.path.join(self.data_dir, img_folder, np.random.choice(os.listdir(os.path.join(self.data_dir, img_folder))))
            label = 0
        # print(img1_path, img2_path, label)
        return img1_path, img2_path, label


    def __data_generation(self, writer_pairs):
        X1_rgb = np.empty((self.batch_size, *self.img_size, self.channels))
        X1_edge = np.empty((self.batch_size, *self.img_size, 1))
        X2_rgb = np.empty((self.batch_size, *self.img_size, self.channels))
        X2_edge = np.empty((self.batch_size, *self.img_size, 1))
        Y = np.empty((self.batch_size,), dtype=int)
        for i, (img1_path, img2_path, label) in enumerate(writer_pairs):
            X1_rgb[i,], X1_edge[i,] = self.load_image(img1_path)
            X2_rgb[i,], X2_edge[i,] = self.load_image(img2_path)
            Y[i] = label
        return self.preprocess_images(X1_rgb), self.preprocess_images(X1_edge), self.preprocess_images(X2_rgb), self.preprocess_images(X2_edge), Y

    def load_image(self, img_path):
        img = tf.keras.preprocessing.image.load_img(img_path, target_size=None, interpolation='bilinear')
        img = img.resize(self.img_size, resample=Image.BILINEAR)
        img = tf.keras.preprocessing.image.img_to_array(img)
        # img_eroded = cv2.erode(img, None, iterations=1)
        # img = cv2.dilate(img_eroded, None, iterations=1)
        # img = img.astype(np.uint8)
        # img = cv2.fastNlMeansDenoisingColored(img, None, h=10, hColor=10, templateWindowSize=7, searchWindowSize=21)


        img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        img_gray_u = img_gray.astype(np.uint8) # Convert to 8-bit unsigned integer

        img_laplacian = cv2.Laplacian(img_gray_u, cv2.CV_64F, 3)
        img_edge = np.expand_dims(img_laplacian, axis=-1)  # Add channel dimension
        return img, img_edge

    def preprocess_images(self, images):
        images = images.astype(np.float32)
        images /= 255.0
        images = np.nan_to_num(images, nan=0.0, posinf=1.0, neginf=0.0)
        return images

train_data_generator = SiameseTrainDataGenerator(batch_size=8, shuffle=True)

"""### Validation Data Generator"""

class SiameseValidationDataGenerator(tf.keras.utils.Sequence):

    def __init__(self, batch_size=16, shuffle=True):
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.data_dir = path_IAM_class_Validation
        self.writer_list = sorted(os.listdir(self.data_dir))
        self.img_size = (150, 150)
        self.channels = 3
        self.num_samples = sum(len(os.listdir(os.path.join(self.data_dir, writer_id))) for writer_id in self.writer_list) * 2 # Each image will one genuine and one forged case
        self.writer_lines_list = self.store_image_paths()
        self.on_epoch_end()

    def store_image_paths(self):
      writer_lines_list = []
      for writer_id in self.writer_list:
          writer_dir = os.path.join(self.data_dir, writer_id)
          image_list = os.listdir(writer_dir)
          for image_name in image_list:
              image_path = os.path.join(writer_dir, image_name)
              writer_lines_list.append(image_path)
      return writer_lines_list


    def __len__(self):
        return int(np.ceil(self.num_samples / float(self.batch_size)))

    def __getitem__(self, idx):
        indexes = self.indexes[idx*self.batch_size : (idx+1)*self.batch_size]
        writer_pairs = [self.get_writer_pair(idx) for idx in indexes]
        X1_rgb, X1_edge, X2_rgb, X2_edge, Y = self.__data_generation(writer_pairs)
        return [X1_rgb, X1_edge, X2_rgb, X2_edge], Y

    def on_epoch_end(self):
        self.indexes = np.arange(self.num_samples)
        if self.shuffle:
            np.random.shuffle(self.indexes)

    def get_writer_pair(self, idx):
        img1_path = self.writer_lines_list[idx//2]
        if idx % 2 == 0:
            img2 = np.random.choice(os.listdir(os.path.join(self.data_dir, img1_path.split('/')[-2])))
            while img2 == img1_path.split('/')[-1]:
              img2 = np.random.choice(os.listdir(os.path.join(self.data_dir, img1_path.split('/')[-2])))
            img2_path = os.path.join(self.data_dir, img1_path.split('/')[-2], img2)
            label = 1
        else:
            img_folder = np.random.choice(self.writer_list)
            while img_folder ==  img1_path.split('/')[-2]:
              img_folder = np.random.choice(self.writer_list)
            img2_path = os.path.join(self.data_dir, img_folder, np.random.choice(os.listdir(os.path.join(self.data_dir, img_folder))))
            label = 0
        # print(img1_path, img2_path, label)
        return img1_path, img2_path, label


    def __data_generation(self, writer_pairs):
        X1_rgb = np.empty((self.batch_size, *self.img_size, self.channels))
        X1_edge = np.empty((self.batch_size, *self.img_size, 1))
        X2_rgb = np.empty((self.batch_size, *self.img_size, self.channels))
        X2_edge = np.empty((self.batch_size, *self.img_size, 1))
        Y = np.empty((self.batch_size,), dtype=int)
        for i, (img1_path, img2_path, label) in enumerate(writer_pairs):
            X1_rgb[i,], X1_edge[i,] = self.load_image(img1_path)
            X2_rgb[i,], X2_edge[i,] = self.load_image(img2_path)
            Y[i] = label
        return self.preprocess_images(X1_rgb), self.preprocess_images(X1_edge), self.preprocess_images(X2_rgb), self.preprocess_images(X2_edge), Y

    def load_image(self, img_path):
        img = tf.keras.preprocessing.image.load_img(img_path, target_size=None, interpolation='bilinear')
        img = img.resize(self.img_size, resample=Image.BILINEAR)
        img = tf.keras.preprocessing.image.img_to_array(img)
        # img_eroded = cv2.erode(img, None, iterations=1)
        # img = cv2.dilate(img_eroded, None, iterations=1)
        # img = img.astype(np.uint8)
        # img = cv2.fastNlMeansDenoisingColored(img, None, h=10, hColor=10, templateWindowSize=7, searchWindowSize=21)


        img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        img_gray_u = img_gray.astype(np.uint8) # Convert to 8-bit unsigned integer

        img_laplacian = cv2.Laplacian(img_gray_u, cv2.CV_64F, 3)
        img_edge = np.expand_dims(img_laplacian, axis=-1)  # Add channel dimension
        return img, img_edge

    def preprocess_images(self, images):
        images = images.astype(np.float32)
        images /= 255.0
        images = np.nan_to_num(images, nan=0.0, posinf=1.0, neginf=0.0)
        return images

Validation_data_generator = SiameseValidationDataGenerator(batch_size=8, shuffle=True)

"""### Test Data Generator"""

class SiameseTestDataGenerator(tf.keras.utils.Sequence):

    def __init__(self, batch_size=16, shuffle=True):
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.data_dir = path_IAM_class_test
        self.writer_list = sorted(os.listdir(self.data_dir))
        self.img_size = (150, 150)
        self.channels = 3
        self.num_samples = sum(len(os.listdir(os.path.join(self.data_dir, writer_id))) for writer_id in self.writer_list)
        self.writer_lines_list = self.store_image_paths()
        self.on_epoch_end()

    def store_image_paths(self):
      writer_lines_list = []
      for writer_id in self.writer_list:
          writer_dir = os.path.join(self.data_dir, writer_id)
          image_list = os.listdir(writer_dir)
          for image_name in image_list:
              image_path = os.path.join(writer_dir, image_name)
              writer_lines_list.append(image_path)
      return writer_lines_list


    def __len__(self):
        return int(np.ceil(self.num_samples / float(self.batch_size)))

    def __getitem__(self, idx):
        indexes = self.indexes[idx*self.batch_size : (idx+1)*self.batch_size]
        writer_pairs = [self.get_writer_pair(idx) for idx in indexes]
        X1_rgb, X1_edge, X2_rgb, X2_edge, Y = self.__data_generation(writer_pairs)
        return [X1_rgb, X1_edge, X2_rgb, X2_edge], Y

    def on_epoch_end(self):
        self.indexes = np.arange(self.num_samples)
        if self.shuffle:
            np.random.shuffle(self.indexes)

    def get_writer_pair(self, idx):
        img1_path = self.writer_lines_list[idx]
        if np.random.random() < 0.5:
            img2 = np.random.choice(os.listdir(os.path.join(self.data_dir, img1_path.split('/')[-2])))
            while img2 == img1_path.split('/')[-1]:
              img2 = np.random.choice(os.listdir(os.path.join(self.data_dir, img1_path.split('/')[-2])))
            img2_path = os.path.join(self.data_dir, img1_path.split('/')[-2], img2)
            label = 1
        else:
            img_folder = np.random.choice(self.writer_list)
            while img_folder ==  img1_path.split('/')[-2]:
              img_folder = np.random.choice(self.writer_list)
            img2_path = os.path.join(self.data_dir, img_folder, np.random.choice(os.listdir(os.path.join(self.data_dir, img_folder))))
            label = 0
        # print(img1_path, img2_path, label)
        return img1_path, img2_path, label


    def __data_generation(self, writer_pairs):
        X1_rgb = np.empty((self.batch_size, *self.img_size, self.channels))
        X1_edge = np.empty((self.batch_size, *self.img_size, 1))
        X2_rgb = np.empty((self.batch_size, *self.img_size, self.channels))
        X2_edge = np.empty((self.batch_size, *self.img_size, 1))
        Y = np.empty((self.batch_size,), dtype=int)
        for i, (img1_path, img2_path, label) in enumerate(writer_pairs):
            X1_rgb[i,], X1_edge[i,] = self.load_image(img1_path)
            X2_rgb[i,], X2_edge[i,] = self.load_image(img2_path)
            Y[i] = label
        return self.preprocess_images(X1_rgb), self.preprocess_images(X1_edge), self.preprocess_images(X2_rgb), self.preprocess_images(X2_edge), Y

    def load_image(self, img_path):
        img = tf.keras.preprocessing.image.load_img(img_path, target_size=None, interpolation='bilinear')
        img = img.resize(self.img_size, resample=Image.BILINEAR)
        img = tf.keras.preprocessing.image.img_to_array(img)
        # img_eroded = cv2.erode(img, None, iterations=1)
        # img = cv2.dilate(img_eroded, None, iterations=1)
        # img = img.astype(np.uint8)
        # img = cv2.fastNlMeansDenoisingColored(img, None, h=10, hColor=10, templateWindowSize=7, searchWindowSize=21)


        img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        img_gray_u = img_gray.astype(np.uint8) # Convert to 8-bit unsigned integer
        img_laplacian = cv2.Laplacian(img_gray_u, cv2.CV_64F, 3)
        img_edge = np.expand_dims(img_laplacian, axis=-1)  # Add channel dimension
        img_gray = np.expand_dims(img_gray, axis=-1)
        return img, img_edge

    def preprocess_images(self, images):
        images = images.astype(np.float32)
        images /= 255.0
        images = np.nan_to_num(images, nan=0.0, posinf=1.0, neginf=0.0)
        return images

test_data_generator = SiameseTestDataGenerator(batch_size=8, shuffle=True)

"""### Visualizing the data"""

# Get a batch of image pairs and their labels
X, Y = train_data_generator.__getitem__(0)

# Extract the individual images from the batch
X1_rgb, X1_edge, X2_rgb, X2_edge = X

# Plot the image pairs and their edges side by side with their corresponding labels
fig, axs = plt.subplots(nrows=len(X1_rgb), ncols=5, figsize=(15, 30))
for i in range(len(X1_rgb)):
    label = 'Genuine' if Y[i] == 1 else 'Forged'
    axs[i, 0].imshow(X1_rgb[i])
    axs[i, 0].axis('off')
    axs[i, 0].set_title('Image 1')
    axs[i, 1].imshow(X1_edge[i,:,:,0], cmap='gray')
    axs[i, 1].axis('off')
    axs[i, 1].set_title(' Laplacian 1')
    axs[i, 2].imshow(X2_rgb[i])
    axs[i, 2].axis('off')
    axs[i, 2].set_title('Image 2')
    axs[i, 3].imshow(X2_edge[i,:,:,0], cmap='gray')
    axs[i, 3].axis('off')
    axs[i, 3].set_title('Laplacian 2')
    axs[i, 4].axis('off')
    axs[i, 4].text(0.5, 0.5, label, fontsize=16, ha='center', va='center')
    fig.suptitle('Siamese image pairs with labels and Laplacian filter', fontsize=16)
plt.show()

"""### Tiny Resnet Architecture"""

# Define the TinyResNet architecture
def tiny_resnet(input_shape):
    n = 1  # Number of residual blocks per stack

    inputs = Input(shape=input_shape)
    x = Conv2D(16, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='relu')(inputs)

    for _ in range(2 * n):
        shortcut = x
        x = Conv2D(16, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='relu')(x)
        x = Conv2D(16, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='relu')(x)
        x = tf.keras.layers.Add()([x, shortcut])
        x = tf.keras.layers.Activation('relu')(x)

    x = Conv2D(32, kernel_size=(3, 3), strides=(2, 2), padding='same', activation='relu')(x)
    for _ in range(2 * n):
        shortcut = x
        x = Conv2D(32, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='relu')(x)
        x = Conv2D(32, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='relu')(x)
        x = tf.keras.layers.Add()([x, shortcut])
        x = tf.keras.layers.Activation('relu')(x)

    x = Conv2D(64, kernel_size=(3, 3), strides=(2, 2), padding='same', activation='relu')(x)
    for _ in range(2 * n):
        shortcut = x
        x = Conv2D(64, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='relu')(x)
        x = Conv2D(64, kernel_size=(3, 3), strides=(1, 1), padding='same', activation='relu')(x)
        x = tf.keras.layers.Add()([x, shortcut])
        x = tf.keras.layers.Activation('relu')(x)

    x = Flatten()(x)
    return inputs, x

"""### ResNet + Laplacian

"""

def make_embedding():
    inp_rgb = Input(shape=(150, 150, 3), name='input_image_rgb')
    resnet = ResNet50(weights='imagenet', include_top=False, input_tensor=inp_rgb)
    f1 = Flatten()(resnet.output)

    inp = Input(shape=(150, 150, 1), name='input_image')
    l1 = Conv2D(filters=32, kernel_size=(3,3), activation='relu')(inp)
    l1 = BatchNormalization()(l1)
    m1 = MaxPooling2D((2, 2), padding='same')(l1)

    # Second Block
    l2 = Conv2D(64,(3,3), activation = 'relu')(m1)
    l2 = BatchNormalization()(l2)
    m2 = MaxPooling2D((2, 2), padding='same')(l2)

    # Third Block
    l3 = Conv2D(128,(3,3), activation='relu')(m2)
    l3 = BatchNormalization()(l3)
    m3 = MaxPooling2D((2,2), padding='same')(l3)

    # Final Block
    l4 = Conv2D(256, (3, 3), activation='relu')(m3)
    l4 = BatchNormalization()(l4)
    out = Flatten()(l4)

    # Concatenate CNN and Canny outputs
    x = Concatenate()([f1, out])
    x = Dense(4096, activation='sigmoid')(x)
    return Model(inputs=[inp_rgb, inp], outputs=x, name='ResNet_Laplacian')

ResNet_Laplacian = make_embedding()
ResNet_Laplacian.summary()

"""### Making the Siamese Model

"""

class Distance(Layer):

    # Init method - Inheritance
    def __init__(self, **kwargs):
        super().__init__()

    #  Similarity Calculation
    def call(self, input_layer, validation_layer):
        return tf.math.abs(input_layer - validation_layer)


def make_Siamese_Model():
    input_image_rgb = Input(shape=(150,150,3), name='input_image_rgb')
    input_image_laplacian = Input(shape=(150,150,1), name='input_image_laplacian')
    validation_image_rgb = Input(shape=(150,150,3), name='validation_image_rgb')
    validation_image_laplacian = Input(shape=(150,150,1), name='validation_image_laplacian')

    distance_layer = Distance()
    siamese_model = make_embedding()
    distances = distance_layer(siamese_model([input_image_rgb, input_image_laplacian]), siamese_model([validation_image_rgb, validation_image_laplacian]))

    # Classifier Layer
    classifier = Dense(1, activation='sigmoid')(distances)

    return Model(inputs=[input_image_rgb, input_image_laplacian, validation_image_rgb, validation_image_laplacian], outputs=classifier, name='SiameseNetwork')

siamese_model = make_Siamese_Model()
siamese_model.summary()

"""### Look at our Model"""

plot_model(siamese_model, to_file='Siamese.png', show_shapes=True, show_layer_names=True)
img = mpimg.imread('Siamese.png')
plt.figure(figsize=(100,70))
imgplot = plt.imshow(img)

"""### Check point, early stop and reduced learning rate"""

checkpoint = ModelCheckpoint(path_save_model,
                             monitor="val_accuracy",
                             mode="max",
                             save_best_only = True,
                             verbose=1)

earlystop = EarlyStopping(monitor = 'val_accuracy',
                          mode='max',
                          patience = 15,
                          verbose = 1,
                          restore_best_weights = True)

reduce_lr = ReduceLROnPlateau(monitor = 'val_accuracy',
                              factor = 0.1,
                              patience = 10,
                              verbose = 1,
                              mode='max',
                              min_lr=0.000001)

# we put our call backs into a callback list
callbacks = [earlystop, checkpoint, reduce_lr]

"""### Training the Model

"""

# # Check if the model exists in the specified directory
# # if os.path.exists(path_save_model):
# if(False):
#     # Load the model and continue training
#     with custom_object_scope({'Distance': Distance}):
#       saved_model = load_model(path_save_model)
#     saved_model.compile(loss='binary_crossentropy', optimizer=Adam(learning_rate=0.000001), metrics=['accuracy'])
#     saved_model.fit(train_data_generator, validation_data=Validation_data_generator, epochs=30, callbacks=callbacks)
# else:
#   # Train a new model from scratch
#   siamese_model.compile(loss='binary_crossentropy', optimizer=Adam(learning_rate=0.00001), metrics=['accuracy'])
#   siamese_model.fit(train_data_generator, validation_data=Validation_data_generator, epochs=30, callbacks=callbacks)

"""### Load Model"""

with custom_object_scope({'Distance': Distance}):
    saved_model = load_model(path_save_model)

"""### Performance Analysis"""

threshold = 0.1
data = []

while threshold < 0.95:
    correct = 0
    incorrect = 0
    true_positive = 0
    true_negative = 0
    false_positive = 0
    false_negative = 0

    for i in range(len(test_data_generator)):
        test_pair = test_data_generator[i]
        predictions = saved_model.predict(test_pair[0], verbose=0)
        rounded_predictions = np.round(predictions, 2)

        for i, value in enumerate(rounded_predictions):
            if value[0] < threshold:
                pred_val = 0
            else:
                pred_val = 1

            if pred_val == test_pair[1][i]:
                if pred_val == 1:
                    true_positive += 1
                else:
                    true_negative += 1
                correct += 1
            else:
                if pred_val == 0:
                    false_negative += 1
                else:
                    false_positive += 1
                incorrect += 1
    print(threshold,correct,incorrect, true_positive, true_negative, false_positive, false_negative)
    accuracy = correct / (correct + incorrect)
    precision = true_positive / (true_positive + false_positive)
    recall = true_positive / (true_positive + false_negative)
    f1_score = 2 * (precision * recall) / (precision + recall)
    print(f"Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1 Score: {f1_score}")
    data.append([threshold, accuracy, precision, recall, f1_score])
    threshold += 0.1

# Create DataFrame from the data list
df = pd.DataFrame(data, columns=["Threshold", "Accuracy", "Precision", "Recall", "F1 Score"])

# Save DataFrame to Excel file
df.to_excel("ResNet_Laplacian_IAM.xlsx", index=False)